### ISSUE TITLE
🔧 React Native Vision Camera v4.7.1 - Compilation Errors with React Native 0.81.0

### ISSUE THREAD

**Issue by OlegSyng** [mrousavy/react-native-vision-camera#3615]
### How were you trying to build the app?

Environment

  - React Native: 0.81.0
  - react-native-vision-camera: 4.7.1
  - Platform: Android
  - Gradle: 8.14.3
  - Android Gradle Plugin: 8.11.0
  - Kotlin: (bundled with gradle)

  Issue Description

  When building an Android app with React Native 0.81.0 and react-native-vision-camera 4.7.1,
  the build fails with Kotlin compilation errors.

  Build Errors

  e: file:///Users/.../node_modules/react-native-vision-camera/android/src/main/java/com/mrousa
  vy/camera/react/CameraViewManager.kt:31:5
  Return type mismatch: expected 'MutableMap<String, Any>?', actual 'Map<String, Any>'.

  e: file:///Users/.../node_modules/react-native-vision-camera/android/src/main/java/com/mrousa
  vy/camera/react/CameraViewModule.kt:192:20
  Unresolved reference 'currentActivity'.

Root Cause

  React Native 0.81.0 has made breaking changes:

  1. ViewManager API Change: The getExportedCustomDirectEventTypeConstants() method now expects
   Map<String, Any>? instead of MutableMap<String, Any>?
  2. ReactContextBaseJavaModule API Change: currentActivity is no longer directly accessible
  and must be accessed through reactApplicationContext.currentActivity

Required Fixes

  File 1: CameraViewManager.kt (line 30)
  // Before (doesn't work with RN 0.81.0)
  override fun getExportedCustomDirectEventTypeConstants(): MutableMap<String, Any>? =

  // After (works with RN 0.81.0)
  override fun getExportedCustomDirectEventTypeConstants(): Map<String, Any>? =

  File 2: CameraViewModule.kt (line 192)
  // Before (doesn't work with RN 0.81.0)
  val activity = currentActivity as? PermissionAwareActivity

  // After (works with RN 0.81.0)
  val activity = reactApplicationContext.currentActivity as? PermissionAwareActivity

  Workaround

  Until an official fix is released, users can apply these changes manually and use
  patch-package to persist them.

  Reproduction Steps

  1. Create a new React Native 0.81.0 project
  2. Install react-native-vision-camera v4.7.1
  3. Run cd android && ./gradlew assembleDebug
  4. Build will fail with the above Kotlin compilation errors

### Full build logs

```tsx
From: ~/.gradle/daemon/8.14.3/daemon-8646.out.log

  Android gradle plugin: 8.11.0
  Gradle: 8.14.3
  [VisionCamera] Thank you for using VisionCamera ❤️
  [VisionCamera] If you enjoy using VisionCamera, please consider sponsoring this project:
  https://github.com/sponsors/mrousavy
  [VisionCamera] node_modules found at /Users/olegsingaevskii/flizpay/payer-app/node_modules
  [VisionCamera] VisionCamera_enableFrameProcessors is set to false!
  [VisionCamera] react-native-worklets-core not found, Frame Processors are disabled!
  [VisionCamera] VisionCamera_enableCodeScanner is set to true!
  No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you
   set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds
  modules.
  e: file:///Users/olegsingaevskii/flizpay/payer-app/node_modules/react-native-vision-camera/an
  droid/src/main/java/com/mrousavy/camera/react/CameraViewManager.kt:31:5 Return type mismatch:
   expected 'MutableMap<String, Any>?', actual 'Map<String, Any>'.
  e: file:///Users/olegsingaevskii/flizpay/payer-app/node_modules/react-native-vision-camera/an
  droid/src/main/java/com/mrousavy/camera/react/CameraViewModule.kt:192:20 Unresolved reference
   'currentActivity'.

  [Incubating] Problems report is available at: file:///Users/olegsingaevskii/flizpay/payer-app
  /android/build/reports/problems/problems-report.html

  FAILURE: Build failed with an exception.

  * What went wrong:
  Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
  > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner
  WithWorkers$GradleKotlinCompilerWorkAction
     > Compilation error. See log for more details
```

### Project dependencies

```json
"dependencies": {
  "react-native": "^0.81.0",
  "react-native-vision-camera": "^4.7.1",
}
```

### VisionCamera Version

4.7.1

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [x] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [x] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by yittoo** [comment]
issue also available under react-native 0.81.1 (non expo)

**Comment by afonsomsalvador** [comment]
✅ Fixed in `react-native-vision-camera` **4.7.2**

**Comment by shaikhkhamroddin** [comment]
> ### How were you trying to build the app?
> Environment
> 
> * React Native: 0.81.0
> * react-native-vision-camera: 4.7.1
> * Platform: Android
> * Gradle: 8.14.3
> * Android Gradle Plugin: 8.11.0
> * Kotlin: (bundled with gradle)
> 
> Issue Description
> 
> When building an Android app with React Native 0.81.0 and react-native-vision-camera 4.7.1, the build fails with Kotlin compilation errors.
> 
> Build Errors
> 
> e: file:///Users/.../node_modules/react-native-vision-camera/android/src/main/java/com/mrousa vy/camera/react/CameraViewManager.kt:31:5 Return type mismatch: expected 'MutableMap<String, Any>?', actual 'Map<String, Any>'.
> 
> e: file:///Users/.../node_modules/react-native-vision-camera/android/src/main/java/com/mrousa vy/camera/react/CameraViewModule.kt:192:20 Unresolved reference 'currentActivity'.
> 
> Root Cause
> 
> React Native 0.81.0 has made breaking changes:
> 
> 1. ViewManager API Change: The getExportedCustomDirectEventTypeConstants() method now expects
>    Map<String, Any>? instead of MutableMap<String, Any>?
> 2. ReactContextBaseJavaModule API Change: currentActivity is no longer directly accessible
>    and must be accessed through reactApplicationContext.currentActivity
> 
> Required Fixes
> 
> File 1: CameraViewManager.kt (line 30) // Before (doesn't work with RN 0.81.0) override fun getExportedCustomDirectEventTypeConstants(): MutableMap<String, Any>? =
> 
> // After (works with RN 0.81.0) override fun getExportedCustomDirectEventTypeConstants(): Map<String, Any>? =
> 
> File 2: CameraViewModule.kt (line 192) // Before (doesn't work with RN 0.81.0) val activity = currentActivity as? PermissionAwareActivity
> 
> // After (works with RN 0.81.0) val activity = reactApplicationContext.currentActivity as? PermissionAwareActivity
> 
> Workaround
> 
> Until an official fix is released, users can apply these changes manually and use patch-package to persist them.
> 
> Reproduction Steps
> 
> 1. Create a new React Native 0.81.0 project
> 2. Install react-native-vision-camera v4.7.1
> 3. Run cd android && ./gradlew assembleDebug
> 4. Build will fail with the above Kotlin compilation errors
> 
> ### Full build logs
> From: ~/.gradle/daemon/8.14.3/daemon-8646.out.log
> 
>   Android gradle plugin: 8.11.0
>   Gradle: 8.14.3
>   [VisionCamera] Thank you for using VisionCamera ❤️
>   [VisionCamera] If you enjoy using VisionCamera, please consider sponsoring this project:
>   https://github.com/sponsors/mrousavy
>   [VisionCamera] node_modules found at /Users/olegsingaevskii/flizpay/payer-app/node_modules
>   [VisionCamera] VisionCamera_enableFrameProcessors is set to false!
>   [VisionCamera] react-native-worklets-core not found, Frame Processors are disabled!
>   [VisionCamera] VisionCamera_enableCodeScanner is set to true!
>   No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you
>    set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds
>   modules.
>   e: file:///Users/olegsingaevskii/flizpay/payer-app/node_modules/react-native-vision-camera/an
>   droid/src/main/java/com/mrousavy/camera/react/CameraViewManager.kt:31:5 Return type mismatch:
>    expected 'MutableMap<String, Any>?', actual 'Map<String, Any>'.
>   e: file:///Users/olegsingaevskii/flizpay/payer-app/node_modules/react-native-vision-camera/an
>   droid/src/main/java/com/mrousavy/camera/react/CameraViewModule.kt:192:20 Unresolved reference
>    'currentActivity'.
> 
>   [Incubating] Problems report is available at: file:///Users/olegsingaevskii/flizpay/payer-app
>   /android/build/reports/problems/problems-report.html
> 
>   FAILURE: Build failed with an exception.
> 
>   * What went wrong:
>   Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
>   > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner
>   WithWorkers$GradleKotlinCompilerWorkAction
>      > Compilation error. See log for more details
> ### Project dependencies
> "dependencies": {
>   "react-native": "^0.81.0",
>   "react-native-vision-camera": "^4.7.1",
> }
> ### VisionCamera Version
> 4.7.1
> 
> ### Target platforms
> Android
> 
> ### Operating system
> MacOS
> 
> ### Can you build the VisionCamera Example app?
> I didn't try (⚠️ your issue might get ignored & closed if you don't try this)
> 
> ### Additional information
> * [ ]  I am using Expo[ ]  I have enabled Frame Processors (react-native-worklets-core)[x]  I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)[x]  I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)[x]  I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.


as I can see error line : >   [VisionCamera] react-native-worklets-core not found, Frame Processors are disabled!
you have missing dependency react-native-worklets-core required for react-native-vision-camera.
kindly install and try.

**Comment by mrousavy** [comment]
Hey! Sorry for the late reply and thank you for your issue report.
I was hyper-focused the entire winter to build the next major version of VisionCamera - and I think [VisionCamera V5](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v5.0.0) fixes this! 🥳

Closing, but feel free to open a new issue if this still needs attention in V5! :)
